network:
    module: "depth_completion"
    name: "ACDC"
    params:
        pretrained: true
        num_scales: 4
        num_layers: 18
        dropblock_prob: 0.1
        fast_decoder: false
        min_depth: 0.3
        max_depth: 20

loader:
    name: "DepthCompletion"
    params:
        min_depth: 0.3
        max_depth: 20
    
dataset: 
    name: "Realsense"
    params:
        data_path: "/data/datasets/d435i/"
        calibration_file: "./deep_learning_trainer/configs/depth_completion/realsense/ucf_d435i_rgb_sem.yaml"
        dist_threshold_min: 0.1
        dist_threshold_max: 1
        angle_threshold: 5
        flexible_thresholds: true

transforms_valtest:
    - CropImage:
        keys:
            - "ir0_curr"
            - "ir0_prev"
            - "ir0_next"
            - "ir1_curr"
            - "ir1_prev"
            - "ir1_next"
            - "depth"
            - "disp"
            - "valid_mask"
            - "sparse_curr"
            - "sparse_best"
            - "sparse_best_valid"
            - "depth_gt"
        crop_top: 0
        crop_left: 0
        height: 480
        width: 832
    - Pyramid:
        num_scales: 4
        height: 480
        width: 832
        antialias_resize_keys:
            - "ir0_curr"
        nearest_resize_keys:
            - "sparse_best"
            - "sparse_best_valid"
    - CopyToAugment:
        keys: {"ir0_curr": "ir0_curr_aug", "disp": "disp_aug", "sparse_curr": "sparse_curr_aug"}
    - Normalize:
        keys: 
            ir0_curr_aug: [[85], [55]]
    - Normalize:
        keys: 
            ir0_curr: [[0], [255]]
            ir0_prev: [[0], [255]]
            ir0_next: [[0], [255]]
            ir1_curr: [[0], [255]]
            ir1_prev: [[0], [255]]
            ir1_next: [[0], [255]]

metrics:
    - DepthMetrics:
        pred_depth_label: "depth"
        min_depth: 0.3
        max_depth: 10

options:
    cudnn_benchmark: True
    tags_write_image:
        - disp_vis
        - depth
