---
cameras:
  - {SensorID: ["Visible", 0],
     T_SC: [ 0.0,  0.0, 1.0, 0.0,
            -1.0,  0.0, 0.0, 0.0,
             0.0, -1.0, 0.0, 0.0,
             0.0,  0.0, 0.0, 1.0],
     focal_length: [320.0, 320.0],
     principal_point: [320.0, 240.0]
    }

  - {SensorID: ["Visible", 1],
     T_SC: [ 0.0,  0.0, 1.0, 0.0,
            -1.0,  0.0, 0.0,-0.25,
             0.0, -1.0, 0.0, 0.0,
             0.0,  0.0, 0.0, 1.0],
     focal_length: [320.0, 320.0],
     principal_point: [320.0, 240.0]
    }

  - {SensorID: ["Depth", 0],
     T_SC: [ 0.0,  0.0, 1.0, 0.0,
            -1.0,  0.0, 0.0, 0.0,
             0.0, -1.0, 0.0, 0.0,
             0.0,  0.0, 0.0, 1.0],
     focal_length: [320.0, 320.0],
     principal_point: [320.0, 240.0]
    }

  - {SensorID: ["Depth", 1],
     T_SC: [ 0.0,  0.0, 1.0, 0.0,
            -1.0,  0.0, 0.0,-0.25,
             0.0, -1.0, 0.0, 0.0,
             0.0,  0.0, 0.0, 1.0],
     focal_length: [320.0, 320.0],
     principal_point: [320.0, 240.0]
    }

imu_params:
  T_BS: # Transform Body-Sensor (IMU)
    [1.0000, 0.0000, 0.0000, 0.0000,
     0.0000, 1.0000, 0.0000, 0.0000,
     0.0000, 0.0000, 1.0000, 0.0000,
     0.0000, 0.0000, 0.0000, 1.0000]

